### ISSUE TITLE
Add octets

### ISSUE THREAD

**Issue by temich** [toa-io/toa#121]
# Change Requests

- [x] #417 
- [x] #426

# Abstract

Binary stream I/O and processing.

- Static streams (files)
- Logical paths
- Content type verification

```yaml
# manifest.toa.yaml
name: pots
exposition:
  /:
    POST: transit
    /:id/photos:
      POST:
        octets:add: photo
      GET:
        octets:list: photo
      /:photo:
        GET:
          octets:fetch: photo

# context.toa.yaml
exsposition:
  octets:
    pots.photo:
      accept:
        - image/jpeg
        - image/png
      storage: photos
      workflow: myfiles.photos.add
```

Octets object:

```yaml
id: ee38402d
path: /pots/b2819a13
type: image/jpeg
```

```yaml
/users/:id/photos:
  auth:id: id
  auth:role: app:moderation:images
  octets:storage: photos
  POST:
    octets:transit:
      workflow:
        - normalize: media.normalize
        - variants: media.diversify
          features: media.analyze
  GET:
    octets:list: ~
  PUT:
    octets:reorder: ~
  /:octets:variant:
    GET:
      octets:stream: ~
    OPTIONS:
      octets:entry: ~
    DELETE:
      octets:delete: ~
```

# Statements

## Logical Paths

```
GET /path/to/photos/ # returns a list of photos
GET /path/to/photos/abcd.meta # returns a photo
```

Should be implemented using S3 aliases.

# Questions

## Which application accepts HTTP requests?

**Option 1: Exposition**

- Common authentication and authorization mechanism

## Which application performs processing?

**Option 1: Services behind the gateway**

- Different media types may require different equipment (memory, GPU, etc).

## Is a stream an entity or an entity's property?

```yaml
name: John
thumbnail: binary jpeg
```

## Which URL is used to upload a file?

Common "upload" or specific?

**Option 1: specific path**

- Different stream requirements (formats) and processing rules

## How streams are passed from the gateway to the processing services?

**By reference**

## How files are being read?

# References

- [sharp](https://sharp.pixelplumbing.com)
