### ISSUE TITLE
feat(amqp): add broker credentials

### ISSUE THREAD

**Issue by temich** [toa-io/toa#159]
It should be possible to secretly use credentials to access an external broker.

# Abstract

Secrets are values for variables.

```yaml
# values.yaml
variables:
  system:
    - name: TOA_BINDINGS_AMQP_SYSTEM_PASSWORD
      secret: 
        - name: toa-bindings-amqp-system
          key: password
  dummies-dummy:
    - name: TOA_CONFIGURATION_STRIPE_API_KEY
      secret: 
        - name: toa-configuration
          key: STRIPE_API_KEY
    - name: TOA_BINDINGS_AMQP_DUMMIES_DUMMY_PASSWORD
      secret: 
        - name: toa-bindings-amqp-dummies-dummy
          key: password
```

> Complexity: 2

# Change Requests

- [x] #168
- [x] #170
- [x] feat(deployment): add system environment variables
- [x] feat(connectors): add extensions
- [x] feat(amqp): add system extension
- [x] feat(deployment): add secrets mapping
- [x] #172
- [x] #173

# Statements

1. Solution must be implemented in Pointer so that it will be standard for all external services.
2. Secrets are values for variables.
3. Solution must be reusable for Configuration. #132 
4. Namespaces cannot have values `default` or `system`
5. System-wide variables must be implemented for the `system` broker.    
6. Values declared with URI Set Annotation must be deployed as variables without expansion. Pointer must resolve URI Set at runtime.

### Credentials Pollution

As components don't declare endpoints they will communicate, each component in the system must know credentials for all brokers. Superimposed that one line annotation for a context with N components `amqp: amqps://host0:5762` expands as `4 x N` variables for each component.

Therefore, the idea to expand was hasty. Values declared with URI Set Annotation must be deployed as variables without expansion. Pointer resolve URI Set at runtime.

> Further, a credentials management system should be provided, or perhaps it's time to take a closer look at Istio.

# Questions

## How to deploy a secret?

`toa conceal <key> <value>` requires to know variable names. This can be the first version.

## Are secrets a part of the configuration solution?

No. Configuration *uses* secrets.

## How to map a secret?

```yaml
variables:
  - name: PASSWORD
    secret: SECRET
```

## How secrets are named?

It's a particular responsibility of the package which uses secrets. Usually the same as the corresponding `variable`.

## How to avoid ambiguity between configuration secrets and objects?

- `TOA_CONFIGURATION_DUMMIES_DUMMY`
- `TOA_CONFIGURATION_SECRET_KEY`

### Option 1: suffix

`TOA_CONFIGURATION_SECRET_VALUE_SECRET_KEY`

### Option 2: prefix

`TOA_SECRET_CONFIGURATION_SECRET_KEY`

### Option 3: weird

`TOA_CONFIGURATIONS_SECRET_KEY`

## Do we need `toa conceal <scope> <key> <value>`?

It doesn't look to simplify the original command.

```shell
kubectl create secret generic configuration \
  --from-literal=STRIPE_API_KEY='S!B\*d$zDsb='
```

It does simplify, as `kubectl` doesn't provide a way to update a key

## Do we need `toa conceal <scope>` to list keys?

Lgtm.
