### ISSUE TITLE
feat(connectors): remove URI Set expansion from deployment

### ISSUE THREAD

**Issue by temich** [toa-io/toa#173]
# Abstract

Pointer deployment must not operate the term `extension`. The object of the deployment is a URI Set.

```yaml
      amqp:
        system: amqps://host0:5671
        dummies.one: amqp://host1
```

```yaml
variables:
  global:
    - name: TOA_BINDINGS_AMQP_POINTER
      value: base64json
    - name: TOA_BINDINGS_AMQP_SYSTEM_USERNAME
      value: secret
    - name: TOA_BINDINGS_AMQP_DUMMIES_ONE_PASSWORD
      value: secret
```

# Change Requests

- [x] refactor(deployment): rename system variables to global variables
- [x] feat(connectors/pointer): replace particular environment variables with POINTER
- [x] feat(connectors/deployment): replace particular environment variables with POINTER
