### ISSUE TITLE
Add IAM

### ISSUE THREAD

**Issue by temich** [toa-io/toa#181]
Exposition extension must provide Identity Authentication and Access Authorization Framework.

# Statements

- IAAA is a part of the Exposition service.
- Exposition must be secure by default. Public resources must be explicitly declared.

# Change Requests

- [x] docs(exposition): add initial documentation
- [x] docs(exposition): add authentication and authorization
- [x] feat(operations): add compositions to extensions
- [x] feat(identity): add `itentity.basic` component
- [x] refactor(exposition)!: add support for HTTP method declarations
- [x] feat(exposition): add authentication
- [x] feat(exposition): add `id` authorization directive
- [x] feat(exposition): add `anonymous` authorization directive
- [x] feat(identity): add `itentity.roles` component
- [x] feat(exposition): add `role` authorization directive
- [x] #396
- [x] feat(identity): add `itentity.tokens` component
- [x] feat(exposition): add `Token` authentication scheme
- [x] feat(exposition): add primary authentication scheme
- [ ] #400
- [x] feat(exposition): add roles to tokens
- [x] feat(exposition): add token rotation
- [x] feat(exposition): add tokens revocation
- [x] feat(exposition): add secret rotation
- [x] feat(exposition): add identity inception
- [x] feat(exposition): add directives to methods
- [x] feat(exposition): add `scheme` directive
- [x] feat(exposition): add `roles` management resources
- [x] feat(exposition): add node isolation
- [x] feat(exposition): isolate identity management resources
- [x] feat(exposition): add `principal`
- [x] feat(exposition): add `username` and `password` constraints
- [x] feat(exposition): add identity blocklist
- [ ] #398
- [ ] #399
- [ ] #397
- [x] docs(exposition): add identity inception
- [x] feat(exposition): add deployment
- [x] feat(exposition): add `/identity` predefined resource
- [x] docs(exposition): add token rotation
- [x] docs(exposition): add `identity.roles` component

# Abstract

Create an Identity:

```http
POST /.identity
Authorization: Basic ...
```

### Policy Declaration

The Component declares Policies that can be bound to Roles within the Context.

```yaml
# manifest.toa.yaml

name: dummy
namespace: dummies

exposition:
  /: 
    operation: create
    policy: admin
  /:user:
    operation: observe
    policy: user
```

### Policy Binding

```yaml
# context.toa.yaml

exposition:
  dummies.dummy:
    roles:
       admin: dummies:editor
```

So, changing Role bindings requires deployment.

### Namespace Policy Binding

Policies are namespace-scoped.

```yaml
# context.toa.yaml

exposition:
  /dummies:
    roles:
       admin: app:editor # bind `dummies.admin` Policy to the `app:editor` Role.
```

### Explicit Resource Directives

```yaml
# context.toa.yaml

exposition:
  /dummies/dummy:
    /:user:
      id: user # allow access for an Identity with `id` matching the `:user` path segment
```

If a resource does not have any authorization directives then it is an Authorization exception.

### Public Access

```yaml
# context.toa.yaml

exposition:
  /dummies/dummy:
    anonymous: true # allow access without Authorization
```

### Authorization scope

1. Authorization rules cascade down the resource tree. 
2. The root node `/` cannot have authorization directives.
3. Components cannot have authorization directives.

# Questions

## Where are Basic credentials stored?

```
# identity.basic
id | username | password
```

## How to change the password?

```http
PUT /.identity/basic

password: new password
```

Same for `username`.

## How to change the password of another Identity? Should it be possible?

```http
PUT /.identity/basic/:id

password: new password
```

## How token data is associated with an Identity?

```
# identity.subjects
id | issuer | subject
```

## Where Identity roles are stored?

```
# identity.roles
identity | role
```

## How to find out Identity roles?

```http
GET /.identity/roles/:id

output: [app:posts:editor]
```

```http
GET /.identity

roles: [app:posts:editor]
```

## How to avoid naming conflicts?

`identity` namespace.

### Option 1: override option

```yaml
# context.toa.yaml

exposition:
  namespace: auth
```
