### ISSUE TITLE
Add storages.amqp

### ISSUE THREAD

**Issue by temich** [toa-io/toa#222]
Implement append-only AMQP storage.

# Change Requests

- [x] feat(core): add event sources
- [x] feat(generic): add `range`
- [x] feat(amqp): add sharded connections
- [x] feat(queues): add `storages.queues`
- [x] feat(boot): add storage connector properties

# Questions

## How to consume events from a queue with an arbitrary name?

Replace `Locator` with `label` in `bindings.Receiver`. Since `bindings.amqp` was refactored to use `ComQ`, the `event.` prefix is no more added.

Keep assuming that `label` meets `namespace.component.label` format for discovery, if no binding is specified.

## How to configure the storage?

Storage must know: 

- the address(es) of AMQP server(s)
- the name of the exchange or queue to "store" entities

```yaml
annotations:
  @toa.io/storages.amqp:
    messages:
      broker: amqp://{0-3}.aws.etc
      exchange: import.messages.created
    users:
      broker: amqp://{0-3}.aws.etc
      exchange: import.users.created
```

## Should an exchange name be part of the Component rather than the Context?

It should, but component annotations are not implemented. Keeping it in the Context.

## How an instance of the storage will know which entity it should "store"?

The same way as other storages: by the convention based on component locator.
