### ISSUE TITLE
 Add the ability to import one yaml file into another

### ISSUE THREAD

**Issue by burlakilia** [toa-io/toa#240]
# Abstract

```yaml
# a.yaml
foo:
  bar: 1
```

```yaml
# b.yaml
qux: 'hello'
foo:
  baz: 2
```

```yaml
# c.yaml
$import: ./*.yaml
```

```javascript
const value = yaml('c.yaml')

console.log(value)

/*
Outputs:

foo:
  bar: 1
  baz: 2
qux: 'hello'
*/
```

> Use [`merge`](https://github.com/toa-io/toa/blob/main/libraries/generic/source/merge.js) from `@toa.io/generic`.
