### ISSUE TITLE
Add absolute URL option to `origins.http`

### ISSUE THREAD

**Issue by temich** [toa-io/toa#269]
# Change Reqeuests

- [x] feat(origins)!: deny absolute URLs
- [x] test(features): add absolute URL feature to `origins`
- [x] feat(origins): add overloaded `invoke` with absolute URL
- [x] feat(origins): add permission settings for absolute URLs

# Statements

## Options 1: setting
![Declined](https://img.shields.io/badge/Declined-red)

```yaml
# context.toa.yaml
origins:
  dummies.dummy:
    .http:
      .any: true
```

## Option 2: regex
![Accepted](https://img.shields.io/badge/Accepted-lightgreen)

```yaml
# context.toa.yaml
origins:
  dummies.dummy:
    .http:
      /.*\.amazon\.com/: true # allowed
      /.*\.azure\.com/: false # forbidden
```
