### ISSUE TITLE
Add `echo` to `origins` URLs

### ISSUE THREAD

**Issue by temich** [toa-io/toa#272]
# Abstract

```bash
$ export STAGE=13
```

```yaml
# manifest.toa.yaml
origins:
  queue: amqp://host${STAGE}.amqp.com
```

# Change Requests

- [ ] feat(generic): add `echo`
- [ ] test(features): add `origins` with `echo`
- [ ] feat(origins): add `echo` to URLs
