### ISSUE TITLE
Yaml $import operation not working at array elements

### ISSUE THREAD

**Issue by burlakilia** [toa-io/toa#310]
# Problem

Load file `loaded.yaml` with $import

**source:** 

```yaml
# loaded.yaml
array:
  - configuration:
       $import: './b.yaml'
```

```yaml
# b.yaml
b: 1
```

**result**
```json
{
    "array": [{ "configuration": { "$import": "./b.yaml" } }]
}
```

**expect**
```json
{
    "array": [{ "configuration": { "b": 1 } }]
}
```
