### ISSUE TITLE
Replay incorrectly passes explicitly given `parameters` to forward

### ISSUE THREAD

**Issue by burlakilia** [toa-io/toa#334]
# Abstract

version: `@toa.io/runtime@0.7.10-dev.17`

**manifest:**
```yaml
operations:
  asset:
    input: object
  users:
    forward: asset
    input:
      .entity: users
      $import: schemas/users.cos.yaml
```

**operation:**
```js
function effect (input) {
   console.log(input['.entity']) // => undefined
}
```
