### ISSUE TITLE
Format type `uri` in schema does not support uri with shards

### ISSUE THREAD

**Issue by burlakilia** [toa-io/toa#343]
# Abstract

```yaml
# context.toa
amqp:
   cp_users@staging: amqp://u-rmq-00{1-5}.030.npdev.lan
```

Run `toa env staging`

`Error`

```
 TypeError: must match format "uri"
```
