### ISSUE TITLE
Refactor Pointer

### ISSUE THREAD

**Issue by temich** [toa-io/toa#373]
# Goals

1. Common shards implementation.
2. Common cluster URLs (arrays) implementation.
3. Remove conflict between the `default` namespace and default Pointer value.
4. Common credentials deployment.
5. Common shards deduplication

# Change Requests

- [x] refactor(pointer): generalize implementation
- [x] refactor(stash): upgrade to the generalized pointer
- [x] refactor(mongo): upgrade to the generalized pointer 
- [x] refactor(amqp): upgrade to the generalized pointer 
- [x] refactor(origins): upgrade to the generalized pointer  
- [x] refactor(pointer): bind credentials to annotation keys
- [x] refactor(sql): upgrade to the generalized pointer  
- [x] feat(cli): add interactive `conceal`
- [x] feat(cli): add interactive `env`
- [x] feat(pointer): add `dedupe` at runtime
- [x] refactor(operations): dedupe common environment variables within composition

# Breaking Changes

- The `amqp` annotation has been divided into `context` and `sources`.
- Receivers' `source` cannot have the value `context`.
- Origins manifest values must be either `uri` or `null`
- Context env variables substitution is now global with syntax: `${{ VAR_NAME }}`
- `storages.queues` has been removed

# Abstract

The Pointer is a mechanism, that can deploy and resolve at runtime a set of named URLs (URL map).

```yaml
# context.toa.yaml
stash: Pointer(stash)

origins:
  dummies.dummy: Pointer(origins-dummies-dummy)

amqp:
  context: Pointer(amqp-context)  # deployed globally by the binding
  sources: Pointer(amqp-{source}) # deployed for components, that request sources
```

```yaml
# context.toa.yaml
stash:
  .: redis://host0
  dummies: redis://host1
  dummies.dummy: redis://host2
```

# Questions

## AMQP binding: component-specific sources?

```yaml
# context.toa.yaml
sources:
  something: Pointer
```

## How components should declare pointer selectors?

With preset value or `null`.

```yaml
# components.toa.yaml
origins:
  some: http://api.example.com
  other: ~
```
