### ISSUE TITLE
Support string array for configuration

### ISSUE THREAD

**Issue by burlakilia** [toa-io/toa#375]
manifest

```
...
configuration:
  some_string_array:
    type: array
    items:
      type: string
....
```

error:
```
Cannot read properties of null (reading '0')
TypeError: Cannot read properties of null (reading '0')
```
