### ISSUE TITLE
feat(realtime): add realtime

### ISSUE THREAD

**Issue by temich** [toa-io/toa#413]
# Abstract

### Static routes

```yaml
# context.toa.yaml
realtime:
  users.updated: id
  messages.created: [sender, recipient]
```

### Dynamic routes

Depends #123 

```javascript
realtime.routes.create({ 
  event: 'rooms.messages.created', 
  key: X,
  value: Y,
  identity: Z
})

realtime.routes.delete({ 
  event: 'rooms.messages.created'
  key: X,
  value: Y,
  identity: Z
})
```

## Observation

```javascript
realtime.streams.observe({ query: { id: X, omit: Y } })
```
