### ISSUE TITLE
Add HTTP request properties mapping

### ISSUE THREAD

**Issue by temich** [toa-io/toa#480]
# Problem

Provide the ability to pass HTTP request parts to operation calls.

# Abstract implementation

Add `negotiation` directives family, with the following directives:

- `languages`: a list of supported languages
- `input`: mapping rules for the request input (in the example below, `texts.observe`)
- predefined negotiators (special mappings):
  - `language`: substitutes best matching language using `languages` directive and `accept-language` header values
  - `ip`: **TDB**
  - any unknown mapping key: raw header value
- headers used by `input` (including implicit use within predefined negotiators) are added to the `Vary` response header value

```yaml
exposition:
  /:
    negotiation:languages: [en, fr]
    /texts/:id:
      GET:
        negotiation:input:
          language: lang        # predefined negotiator
          ip: ip                # predefined negotiator
          x-access-token: token # raw http header value
        endpoint: texts.observe
```

Request object example for the definition above:

```yaml
input:
  language: fr
  ip: 192.168.0.1
  x-access-token: HGGh8vOjL0d-8Vqik83A1S570Hddl68xvoiEpzHZVY
```

**Comment by temich** [comment]
@tinovyatkin @maxacoustic @AirCrisp rfc

**Comment by tinovyatkin** [comment]
Overall, mapping template is great to have feature that would solve bunch of existing problems naturally (for example we can have intermittent implementation of `if-match` using HTTP headers).

For the reference [mapping templates in AWS API Gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/rest-api-data-transformations.html) are extremely powerful and using Apache VTL templates. 
While I'm not proposing to implement something that complex, I do believe we would need at least simple transformations like [expressions in Azure syntax](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops) (I would say bare minimum would be `lower`, `split` / `join`, `replace` and ideally `format`).

Additionally, I believe using wording `negotiation` is misleading in this setting as [Content Negotiation in HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation) has very particular meaning and set of headers while here we want broader access from `Accept-Language` all the way down to custom `X-*` headers or `Date`. So something like simple `request -> mapping` would be easier to follow (and opens a future opportunity to have response mapping if needed).

Last but not least, I found very useful while working with AWS API Gateway being able to also know identity / auth context values, like whether or not original request is authenticated and authentication scheme, and may be credential claims like roles, scopes, etc.

**Comment by temich** [comment]
> For the reference [mapping templates in AWS API Gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/rest-api-data-transformations.html) are extremely powerful and using Apache VTL templates. While I'm not proposing to implement something that complex, I do believe we would need at least simple transformations like [expressions in Azure syntax](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops) (I would say bare minimum would be `lower`, `split` / `join`, `replace` and ideally `format`).

While I believe transformations/expressions is a great feature and it must be provided by the Exposition, I'd suggest to postpone its implementation until we'll have a real product task for it.

I agree with [this](https://neugierig.org/software/blog/2018/07/options.html), btw.
 
> Additionally, I believe using wording `negotiation` is misleading in this setting as [Content Negotiation in HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation) has very particular meaning and set of headers while here we want broader access from `Accept-Language` all the way down to custom `X-*` headers or `Date`. So something like simple `request -> mapping` would be easier to follow (and opens a future opportunity to have response mapping if needed).

The essence of the naming is that if someone wants to pass parts of an HTTP request to an operation, he does that for a reason, that is, the behaviour of an application will differ (and most likely a response will).

I'd say that from this point of view, the naming is in compliance with the abstract part of the HTTP Content Negotiation. While of course it is not the same mechanism, they both serve the same purpose. They both affect `Vary` header, for example (and `mapping` doesn't reflect that).

Let's try to find a better name, considering what was mentioned above.

> Last but not least, I found very useful while working with AWS API Gateway being able to also know identity / auth context values, like whether or not original request is authenticated and authentication scheme, and may be credential claims like roles, scopes, etc.

[One](https://github.com/toa-io/toa/blob/dev/extensions/exposition/documentation/identity.md#faq) of the essential concepts of the Exposition, is that authentication and authorization layer cannot be a part of business logic. "Who is making the request" and "whose data is affected" cannot be the same thing.

All solutions I've seen that were utilizing authentication identity, roles, etc in my experience were eventually refactored to authentication-neutral solutions as they caused either cacheability, or security issues.

That is, while the solution does not prevent anyone to use mapping for the `authorization` request header, I'd prefer not to provide any tools that will provoke developers to do so.

**Comment by temich** [comment]
@tinovyatkin 

Another option for the family name is `vary`.

```yaml
exposition:
  /:
    vary:languages: [en, fr]
    /texts/:id:
      GET:
        vary:input:
          language: lang        # predefined negotiator
          ip: ip                # predefined negotiator
          x-access-token: token # raw http header value
        endpoint: texts.observe
```

**Comment by tinovyatkin** [comment]
I may have some misunderstanding on the concept but `Vary` looks even more confusing to me. Why can't we call mapping settings `mapping` ?

```yaml
exposition:
  /:
    request:mapping:searchparams:
      age: age
      sex: gender

    /texts/:id:
      GET:
        request:mapping:headers:
          language: lang        # predefined negotiator
          ip: ip                # predefined negotiator
          x-access-token: token # raw http header value
        endpoint: texts.observe

   /me
     GET
       request:mapping:identity
         claims.groups: groups
````
