### ISSUE TITLE
Add resources template

### ISSUE THREAD

**Issue by temich** [toa-io/toa#68]
```yaml
  resources:
    /:
      operations: [transit, observe]
    /:id:
      operations: [transit, observe, assign]
```

Definitions options:
```yaml
  resources:
    /: ~
```
```yaml
  resources: ~
```
