### ISSUE TITLE
Add WebAuthn support

### ISSUE THREAD

**Issue by temich** [toa-io/toa#798]
# Entity

```yaml
id: string // Credential ID
origin: string
identity: string
key: string
counter: number
transports: string[]
```

# Resources

## Registration

```
POST /identity/passkeys/:identity/challenges/
```

ExcludeCredentials.

```
POST /identity/passkeys/:identity/

credentials
```

## Authentication

```
POST /identity/passkeys/challenges/
```

```
POST /identity/passkeys/

credentials
```
