### ISSUE TITLE
Add emails

### ISSUE THREAD

**Issue by temich** [toa-io/toa#823]
# Abstract

## Plain

```js
context.mail.send({
  to: 'alice@users.com',
  plain: 'hello',
  await: true // send email as a command instead of a task
})
```

## Template

```js
context.mail.send({
  to: 'alice@users.com',
  template: 'hello',
  data: {
    otp: '123456',
    user: {
      name: 'Alice',
      picture: 'https://pictures.com/alice.jpg'
    }
  }
})
```

### Template rendering

```
POST {baseUrl}/{template}
content-type: application/json

{
  otp: '123456',
  user: {
    name: 'Alice',
    picture: 'https://pictures.com/alice.jpg'
  }
}
```

## Configuration

```yaml
# context.toa.yaml
mail:
  templates: http://localhost:5173/email/
  provider: resend
  from: noreply@domain.com
```
