### ISSUE TITLE
Add throttling

### ISSUE THREAD

**Issue by temich** [toa-io/toa#839]
# Concept

```yaml
exposition:
  /:
    io:throttle:
      key:
        - route
        - ip
        - identity
        - /:segment
        - :header
        - status: [4xx, 5xx]
      requests: 500
      interval: 30
      cooldown: 30
      status: 429
```
